package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Classes;
import lt.vu.mybatis.model.Subjects;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASSES
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASSES
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASSES
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    Classes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASSES
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    List<Classes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASSES
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int updateByPrimaryKey(Classes record);

}