package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Students;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    Students selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    List<Students> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTS
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    int updateByPrimaryKey(Students record);

    List<Students> selectStudentsBySubject(Integer classId);
}