package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.StudentSubjects;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentSubjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_SUBJECTS
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    int insert(StudentSubjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_SUBJECTS
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    List<StudentSubjects> selectAll();
}