package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Subjects;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SubjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int insert(Subjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    Subjects selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    List<Subjects> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int updateByPrimaryKey(Subjects record);

    List<Subjects> selectSubjectsByStudents(Integer studentsId);

    List<Subjects> selectSubjectsByStudentsFree(Integer studentsId);
}