package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Teacher;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEACHER
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    int updateByPrimaryKey(Teacher record);
}