package lt.vu.mybatis.model;

public class Classes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLASSES.NAME
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLASSES.TEACHER_ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLASSES.ID
     *
     * @return the value of PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLASSES.ID
     *
     * @param id the value for PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLASSES.NAME
     *
     * @return the value of PUBLIC.CLASSES.NAME
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLASSES.NAME
     *
     * @param name the value for PUBLIC.CLASSES.NAME
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLASSES.TEACHER_ID
     *
     * @return the value of PUBLIC.CLASSES.TEACHER_ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLASSES.TEACHER_ID
     *
     * @param teacherId the value for PUBLIC.CLASSES.TEACHER_ID
     *
     * @mbg.generated Mon May 04 13:20:20 EEST 2020
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}