package lt.vu.mybatis.model;

public class StudentSubjects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_SUBJECTS.STUDENTLIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    private Integer studentlistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_SUBJECTS.SUBJECT_LIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    private Integer subjectListId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_SUBJECTS.STUDENTLIST_ID
     *
     * @return the value of PUBLIC.STUDENT_SUBJECTS.STUDENTLIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    public Integer getStudentlistId() {
        return studentlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_SUBJECTS.STUDENTLIST_ID
     *
     * @param studentlistId the value for PUBLIC.STUDENT_SUBJECTS.STUDENTLIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    public void setStudentlistId(Integer studentlistId) {
        this.studentlistId = studentlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_SUBJECTS.SUBJECT_LIST_ID
     *
     * @return the value of PUBLIC.STUDENT_SUBJECTS.SUBJECT_LIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    public Integer getSubjectListId() {
        return subjectListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_SUBJECTS.SUBJECT_LIST_ID
     *
     * @param subjectListId the value for PUBLIC.STUDENT_SUBJECTS.SUBJECT_LIST_ID
     *
     * @mbg.generated Mon May 04 22:43:23 EEST 2020
     */
    public void setSubjectListId(Integer subjectListId) {
        this.subjectListId = subjectListId;
    }
}