package lt.vu.mybatis.model;

public class Students {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTS.ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTS.FIRST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTS.LAST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTS.STUDENT_CODE
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    private Long studentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTS.CLASS_GROUP_ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    private Integer classGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTS.ID
     *
     * @return the value of PUBLIC.STUDENTS.ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTS.ID
     *
     * @param id the value for PUBLIC.STUDENTS.ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTS.FIRST_NAME
     *
     * @return the value of PUBLIC.STUDENTS.FIRST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTS.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.STUDENTS.FIRST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTS.LAST_NAME
     *
     * @return the value of PUBLIC.STUDENTS.LAST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTS.LAST_NAME
     *
     * @param lastName the value for PUBLIC.STUDENTS.LAST_NAME
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTS.STUDENT_CODE
     *
     * @return the value of PUBLIC.STUDENTS.STUDENT_CODE
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public Long getStudentCode() {
        return studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTS.STUDENT_CODE
     *
     * @param studentCode the value for PUBLIC.STUDENTS.STUDENT_CODE
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public void setStudentCode(Long studentCode) {
        this.studentCode = studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTS.CLASS_GROUP_ID
     *
     * @return the value of PUBLIC.STUDENTS.CLASS_GROUP_ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public Integer getClassGroupId() {
        return classGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTS.CLASS_GROUP_ID
     *
     * @param classGroupId the value for PUBLIC.STUDENTS.CLASS_GROUP_ID
     *
     * @mbg.generated Tue May 05 02:59:09 EEST 2020
     */
    public void setClassGroupId(Integer classGroupId) {
        this.classGroupId = classGroupId;
    }
}